gemfile:
  - gemfiles/Gemfile.rack-1.x
  - gemfiles/Gemfile.rack-2.x
rvm:
  - '2.3.8'
  - '2.4.6'
  - '2.5.5'
  - '2.6.3'
  - '2.7.0-preview1'
sudo: false
cache: bundler
matrix:
  allow_failures:
    - rvm: 2.7.0-preview1
