gemfile:
  - gemfiles/Gemfile.rack-2.x
  - gemfiles/Gemfile.rack-3.x
rvm:
- 2.1.5
- 2.2.2
- 2.3.3
- 2.4.1
sudo: false
cache: bundler
matrix:
  allow_failures:
    - rvm: 2.1.5 # incompatible with the new jeweler version
