name: Validate
on:
  workflow_call:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - '2.5'
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.2'
          - '3.3'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: |
          bundle exec rspec
