name: Validate
on:
  workflow_call:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem update --system
          gem install bundler
          bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

      - name: Run tests
        run: |
          bundle exec rspec
